# Generated by Django 2.0.7 on 2019-02-18 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0003_auto_20190218_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Const',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('child_benefit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax_exempt_amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shift_right_ratio', models.DecimalField(decimal_places=3, max_digits=3)),
                ('commute_right_ratio', models.DecimalField(decimal_places=3, max_digits=3)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseInfo.Employer')),
            ],
        ),
    ]
