# Generated by Django 2.0.7 on 2019-02-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0004_const_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='const',
            name='child_benefit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='const',
            name='tax_exempt_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
