# Generated by Django 2.0.7 on 2019-02-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0005_auto_20190218_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Employer',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='JobPlace',
            new_name='jobPlace',
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseInfo.Group'),
        ),
    ]
