# Generated by Django 2.0.7 on 2019-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0007_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='desctiption',
            field=models.TextField(null=True),
        ),
    ]
