# Generated by Django 2.0.7 on 2019-02-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0008_auto_20190220_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='desctiption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
