# Generated by Django 2.0.7 on 2019-02-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WageSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('number_of_workers', models.IntegerField()),
                ('sum_gross_amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('sum_tax_amount', models.DecimalField(decimal_places=10, max_digits=50)),
            ],
        ),
    ]
